# Generated by Django 6.1 on 2026-09-03 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='learning_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
