# Generated by Django 6.1 on 2026-09-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userskill',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
